Protoe Robust video matting

diff --git a/scripts/psh b/scripts/psh
--- a/scripts/psh
+++ b/scripts/psh
@@ -47,11 +47,71 @@ params_black_video(){
 
 }
 
+
+
 generate_black_video(){
     duration=$1
     output=$2
     command=$(header && params_black_video $duration $output)
     $command
+    if (( $? != 0 )); then
+        echo "error with $1" >&2
+        return $1
+    fi
+
+}
+
+
+
+params_extract_audio(){
+    local input=$1
+    local output=$2
+
+    echo -n \
+        -i $input \
+        -vn \
+        -acodec copy \
+        $output
+
+}
+
+
+
+extract_audio(){
+    local input=$1
+    local output=$2
+    cmd=$(header && params_extract_audio $input $output)
+    echo $cmd >&2
+    $cmd
+    if (( $? != 0 )); then
+        echo "error with $1" >&2
+        return $1
+    fi
+
+}
+
+merge_audio_video(){
+    params_merge_audio_video(){
+
+        local input_video=$1
+        local input_audio=$2
+        local output=$3
+
+        echo -n \
+            -i $input_video \
+            -i $input_audio \
+            -c:v copy \
+            -c:a aac \
+            $output
+        }
+
+
+    local input_video=$1
+    local input_audio=$2
+    local output=$3
+    cmd=$(header && params_merge_audio_video  $input_video $input_audio $output)
+    echo $cmd >&2
+    $cmd
     if (( $? != 0 )); then
         echo "error with $1" >&2
         return $1
@@ -66,10 +126,11 @@ generate_black_video(){
 #   transcode_video  invideo.mp4  mode  tmp/video.mp4
 transcode_video() {
 
-    input=$1
-    mode=$2
-    output=$3
+    local input=$1
+    local mode=$2
+    local output=$3
 
+    echo "input = $input, mode = $mode, output=$output" >&2
     fps="25"
     vcodec="$vcodec264"
     vcodec_opts="-crf 15"
@@ -162,6 +223,11 @@ get_alpha()
 
 get_keycolor()
 {
+
+if (( $? != 0 )); then
+            echo "error with $1" >&2
+            return $1
+        fi
 
     echo  $(echo $1| jq -cr ".keycolor")
 }
@@ -274,7 +340,10 @@ params_pip_slide_record() {
     color=$(get_keycolor "$webcam_settings")
 
     if [[  "$color" != "null" ]]; then
-        keying_filter=$(colorkey $color)
+        matted_record=$(do_matting $record)
+        echo "matted_record $matted_record" >&2
+        keying_filter=$(colorkey "#79FF9C")
+        record=$matted_record
     fi
     pointer_filter=$(colorkey black)
 
@@ -368,6 +437,73 @@ params_pip_slide_record() {
          $output
 
 
+}
+
+
+
+
+do_matting() {
+
+    INFERENCE_PATH="/home/polymny/dev/git/github/PeterL1n/RobustVideoMatting "
+    record=$1
+
+    filename=$(basename -- "$record")
+    extension="${filename##*.}"
+    filename="${filename%.*}"
+    record_basedir="${record%/*}"
+    record_mp4="${record_basedir}/${filename}.mp4"
+    record_aac="${record_basedir}/${filename}.aac"
+
+    local output="${record_basedir}/${filename}_matted.mp4"
+
+
+    ### Convert webm record to mp4
+    ### TODO convert on more efficient way ? no trnscode of video
+    cmd=$(header && transcode_video $record "blob" $record_mp4)
+    echo $cmd >&2
+    $cmd
+
+    if (( $? != 0 )); then
+            echo "error with $1" >&2
+            return $1
+        fi
+
+
+    # extract audio
+    echo "\n EXTRACT AUDIO \n " >&2
+    extract_audio $record_mp4 $record_aac
+
+    current_dir=$PWD
+
+
+    inference=$(echo python inference.py \
+    --variant mobilenetv3 \
+    --checkpoint "/home/polymny/dev/models/PyTorch/rvm_mobilenetv3.pth" \
+    --device cuda \
+    --input-source "$record_mp4" \
+    --output-type video \
+    --output-composition "${record_basedir}/${filename}_composition.mp4" \
+    --output-alpha "${record_basedir}/${filename}_alpha.mp4" \
+    --output-foreground "${record_basedir}/${filename}_foreground.mp4" \
+    --output-video-mbps 4 \
+    --seq-chunk 15
+    )
+
+    cd $INFERENCE_PATH
+
+    echo $inference >&2
+    $inference 1>&2
+    ### TODO test if infererence goes wrong
+
+
+
+    cd $current_dir
+    echo "\n MERGE AUDIO VIDEO \n " >&2
+    merge_audio_video "${record_basedir}/${filename}_composition.mp4" $record_aac $output
+
+    echo "\n MATTING \n " >&2
+    echo $output >&2
+    echo $output
 }
 
 
@@ -1220,7 +1356,7 @@ main() {
             ;;
         "on-produce")
             read -r capsule_structure
-            #DEBUG echo "$capsule_structure" | jq . >&2
+            echo "$capsule_structure" | jq . >&2
             on-produce "$@"
             ;;
         "on-publish")
